name: tarot_ai
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.2+170825147

environment:
  sdk: ">=3.3.0 <4.0.0"

# -------- תלויות שהאפליקציה צריכה כדי לרוץ --------
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0

  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0

  firebase_app_check: ^0.3.0+3

  video_player: ^2.8.6
  
  # הוספנו את החבילה החיונית לתרגום
  flutter_localizations:
    sdk: flutter
  
  flutter_svg: ^2.0.7
  
  # תלויות Firebase
  firebase_core: ^3.15.2
  cloud_functions: ^5.1.4

  path_provider: 2.1.3

  # חבילה חלופית לזיהוי דיבור
  flutter_speech: ^2.0.1

  # חבילות נוספות
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  intl: ^0.20.2 
  firebase_storage: ^12.4.9
  http: ^1.2.2
  firebase_crashlytics: ^4.3.10
  firebase_performance: ^0.10.1+10



# -------- תלויות לפיתוח ובנייה בלבד --------
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# -------- הגדרות כלליות של Flutter --------
flutter:
  generate: true
  uses-material-design: true

  # הגדרת תיקיית הנכסים (assets)
  assets:
    - assets/images/
    - assets/tarot/
    - assets/videos/

# -------- הגדרות ספציפיות לחבילת האייקונים --------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/taroticon.png"

# -------- הגדרות ספציפיות לחבילת מסך הפתיחה --------
flutter_native_splash:
  color: "#000000"
  image: "assets/images/taroticon.png" # עודכן ל-PNG לאחידות
  android: true
  ios: true